---
# https://github.com/troessner/reek/blob/master/docs/Code-Smells.md
detectors:
  UncommunicativeVariableName:
    enabled: true
    accept:
      - k
      - v
      - _
      - i
  TooManyStatements:
    enabled: true
    max_statements: 10
