---
# https://www.rubocop.org/en/latest/cops_layout/
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
require: rubocop-performance
AllCops:
  TargetRubyVersion: 2.5
Naming/UncommunicativeBlockParamName:
  AllowedNames:
    - k
    - v
