(setq custom-prefix "C-S-")
(mapc
 (lambda (shortcut)
   (global-set-key (kbd (concat custom-prefix (car shortcut)))
		   (cdr shortcut)))
 (list
  (cons "o" 'other-window)
  (cons "k" 'kill-this-buffer)
  (cons "w" 'kill-buffer-and-window)
  (cons ")" 'delete-window)
  (cons "!" 'delete-other-windows)
  (cons "@" 'split-window-below)
  (cons "#" 'split-window-right)
  (cons "e" 'eshell)
  (cons "r" 'ido-recentf-open)
  (cons "z" 'sr-speedbar-open-and-select)
  (cons "f" 'find-file)
  (cons "s" 'save-buffer)
  (cons "b" 'switch-to-buffer)
  (cons "c" 'caps-lock-mode)
  (cons "x" 'kmacro-end-or-call-macro)
  (cons "g d" 'ecb-goto-window-directories)
  (cons "g s" 'ecb-goto-window-sources)
  (cons "g h" 'ecb-goto-window-history)
  (cons "g m" 'ecb-goto-window-methods)))

(global-set-key (kbd "M-g") 'goto-line)

